// components/Avatar.vue
<template lang="pug">
  div(:class="$style.root")
    img(:class="$style.image" src="~/assets/images/avatar.png")
</template>

<style lang="scss" module>
.root {
  --width: 120px;
  display: block;
  padding: 10px;
  border-radius: 999px;
  height: var(--width);
  width: var(--width);
  background-color: #e4e4e4;
}

.image {
  width: 100%;
  border-radius: 999px;
  opacity: 0.8;
}
</style>

// src/components/atoms/Avatar/Avatar.tsx
import { styled } from '@compiled/react';
import AvatarPNG from './avatar.png'

export const Avatar = () => {
  return (
    <Root>
      <Image src={ AvatarPNG } />
    </Root>
  )
}

const Root = styled.header`
  --width: 120px;

  display: block;
  width: var(--width);
  height: var(--width);
  padding: 10px;
  background-color: #e4e4e4;
  border-radius: 999px;
`

const Image = styled.img`
  width: 100%;
  border-radius: 999px;
  opacity: 0.8;
`
