// src/components/molecules/ProfileLinks.tsx
import { styled } from '@compiled/react';
import { ProfileLink } from '../atoms/ProfileLink'

export const ProfileLinks = () => {
  return (
    <Root>
      <ProfileLink ligatureName="twitter" href="https://twitter.com/ruedap" />
      <ProfileLink ligatureName="github" href="https://github.com/ruedap" />
      <ProfileLink ligatureName="mail" href="mailto:ruedap@ruedap.com" />
    </Root>
  )
}

const Root = styled.nav`
  display: flex;
  flex-direction: column;
  margin-top: 24px;
`

// components/molecules/ProfileLinks.vue
<template lang="pug">
div(:class="$style.root")
  profile-link(name="twitter" href="https://twitter.com/ruedap")
  profile-link(name="github" href="https://github.com/ruedap")
  profile-link(name="mail" href="mailto:ruedap@ruedap.com")
</template>

<script>
import ProfileLink from '~/components/atoms/ProfileLink.vue'
export default {
  components: {
    ProfileLink
  }
}
</script>

<style lang="scss" module>
.root {
  margin-top: 24px;
  display: flex;
  flex-direction: column;
}
</style>
