// components/organisms/PageHeader.vue
<template lang="pug">
div(:class="$style.root")
  logo
  avatar(:class="$style.avatar")
  profile-links
</template>

<script>
import Logo from '~/components/atoms/Logo.vue'
import Avatar from '~/components/atoms/Avatar.vue'
import ProfileLinks from '~/components/molecules/ProfileLinks.vue'
export default {
  components: {
    Logo,
    Avatar,
    ProfileLinks
  }
}
</script>

<style lang="scss" module>
.root {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.avatar {
  margin-top: 4rem;
}
</style>

// src/components/molecules/PageHeader.tsx
import { styled } from '@compiled/react';
import { Logo } from '../atoms/Logo'
import { Avatar } from '../atoms/Avatar'
import { ProfileLinks } from '../molecules/ProfileLinks'
import { Spacer } from '../atoms/Spacer'

export const PageHeader = () => {
  return (
    <Root>
      <Logo />
      <AvatarStyled />
      <Spacer height={ 24 } />
      <ProfileLinks />
    </Root>
  )
}

const Root = styled.header`
  display: flex;
  flex-direction: column;
  align-items: center;
`

const AvatarStyled = styled(Avatar)`
  margin-top: 4rem;
`
